import Foundation

/// A fully-buffered request to the control plane. Control requests are small
/// (the server caps bodies), so buffering here is deliberate; proxied traffic
/// never goes through this type.
public struct ControlRequest: Sendable {
    public var method: String
    /// The raw request target, e.g. `/api/v1/apps?x=1`.
    public var uri: String
    /// Header values keyed by lowercased name; repeated headers comma-joined.
    public var headers: [String: String]
    public var body: Data

    public init(method: String, uri: String, headers: [String: String] = [:], body: Data = Data()) {
        self.method = method.uppercased()
        self.uri = uri
        self.headers = Dictionary(headers.map { ($0.key.lowercased(), $0.value) }, uniquingKeysWith: { "\($0), \($1)" })
        self.body = body
    }

    /// The path without query string, percent-decoded, trailing slash trimmed.
    public var path: String {
        let raw = uri.split(separator: "?", maxSplits: 1, omittingEmptySubsequences: false).first.map(String.init) ?? uri
        let decoded = raw.removingPercentEncoding ?? raw
        if decoded.count > 1, decoded.hasSuffix("/") {
            return String(decoded.dropLast())
        }
        return decoded.isEmpty ? "/" : decoded
    }

    public func header(_ name: String) -> String? {
        headers[name.lowercased()]
    }
}

/// A complete response generated by Subpanel itself (API, docs, error pages).
public struct LocalResponse: Sendable {
    public var status: Int
    public var headers: [(name: String, value: String)]
    public var body: Data

    public init(status: Int, headers: [(name: String, value: String)] = [], body: Data = Data()) {
        self.status = status
        self.headers = headers
        self.body = body
    }

    public func header(_ name: String) -> String? {
        headers.first { $0.name.caseInsensitiveCompare(name) == .orderedSame }?.value
    }

    public static func json(_ value: some Encodable, status: Int = 200) -> LocalResponse {
        let body = (try? APICoding.encoder.encode(value)) ?? Data("{}".utf8)
        return LocalResponse(
            status: status,
            headers: [("Content-Type", "application/json; charset=utf-8")],
            body: body + Data("\n".utf8)
        )
    }

    public static func error(_ error: SubpanelError) -> LocalResponse {
        json(ErrorEnvelope(error), status: error.code.httpStatus)
    }

    public static func markdown(_ text: String, status: Int = 200) -> LocalResponse {
        LocalResponse(status: status, headers: [("Content-Type", "text/markdown; charset=utf-8")], body: Data(text.utf8))
    }

    public static func html(_ text: String, status: Int = 200) -> LocalResponse {
        LocalResponse(status: status, headers: [("Content-Type", "text/html; charset=utf-8")], body: Data(text.utf8))
    }

    public static func text(_ text: String, status: Int = 200) -> LocalResponse {
        LocalResponse(status: status, headers: [("Content-Type", "text/plain; charset=utf-8")], body: Data(text.utf8))
    }

    public static func noContent() -> LocalResponse {
        LocalResponse(status: 204)
    }
}

/// Crude but predictable content negotiation over the `Accept` header.
public enum Negotiation {
    /// A browser navigation: asks for HTML and not for Markdown. Agents'
    /// fetchers that ask for Markdown (or `*/*`, like curl) get Markdown.
    public static func prefersHTML(_ accept: String?) -> Bool {
        guard let accept = accept?.lowercased() else { return false }
        return accept.contains("text/html") && !accept.contains("text/markdown")
    }

    public static func prefersJSON(_ accept: String?) -> Bool {
        guard let accept = accept?.lowercased() else { return false }
        return accept.contains("application/json") && !accept.contains("text/html")
    }
}
