import Foundation

/// Server-rendered HTML for browsers: the status page at `subpanel.localhost`,
/// the rendered instructions, and the 404/502 pages. Deliberately tiny — the
/// real management UI is native (plans/design-system.md, "HTML pages").
public enum Pages {
    public struct Status: Sendable {
        public var version: String
        public var apps: [AppDTO]
        public var port: Int

        public init(version: String, apps: [AppDTO], port: Int) {
            self.version = version
            self.apps = apps
            self.port = port
        }
    }

    public static func status(_ status: Status) -> String {
        let base = SubpanelConstants.controlBaseURL(port: status.port)
        let rows = status.apps.map { app in
            let state = switch app.reachable {
            case true: "<span class=\"up\">●</span> Responding"
            case false: "<span class=\"down\">○</span> Not responding"
            default: ""
            }
            return """
                <tr><td><a href="\(e(app.url))">\(e(app.name))</a></td>\
                <td class="mono">\(e(app.target.replacingOccurrences(of: "http://", with: "")))</td>\
                <td class="meta">\(state)</td></tr>
                """
        }.joined(separator: "\n")
        let appsSection = status.apps.isEmpty
            ? "<p class=\"meta\">No apps registered yet.</p>"
            : "<table><thead><tr><th>App</th><th>Target</th><th>Status</th></tr></thead><tbody>\n\(rows)\n</tbody></table>"
        let body = """
            <header>
              <h1>Subpanel</h1>
              <p class="meta">Proxy running · \(status.apps.count) \(status.apps.count == 1 ? "app" : "apps") · version \(e(status.version))</p>
            </header>
            <section>
              <h2>Apps</h2>
              \(appsSection)
            </section>
            <section>
              <h2>For coding agents</h2>
              <p>To give a local web app a URL, follow the instructions at \
            <a href="\(base)/instructions">\(base)/instructions</a>. \
            The API status is at <a href="\(base)/api/v1/status">\(base)/api/v1/status</a>.</p>
            </section>
            """
        return page(title: "Subpanel", body: body)
    }

    public static func instructions(markdown: String) -> String {
        page(title: "Subpanel · Agent instructions", body: "<article>\n\(MarkdownHTML.render(markdown))\n</article>")
    }

    /// A 4xx/5xx page generated by Subpanel (never by a backend).
    public static func problem(title: String, message: String, details: [(String, String)] = [], hint: String? = nil, port: Int) -> String {
        let base = SubpanelConstants.controlBaseURL(port: port)
        let detailRows = details.map { "<dt>\(e($0.0))</dt><dd class=\"mono\">\(e($0.1))</dd>" }.joined()
        let body = """
            <header><h1>\(e(title))</h1></header>
            <p>\(e(message))</p>
            \(details.isEmpty ? "" : "<dl>\(detailRows)</dl>")
            \(hint.map { "<p>\(MarkdownHTML.inline($0))</p>" } ?? "")
            <p class="meta">Served by <a href="\(base)/">Subpanel</a> · <a href="\(base)/instructions">agent instructions</a></p>
            """
        return page(title: title, body: body)
    }

    private static func e(_ text: String) -> String { MarkdownHTML.escape(text) }

    private static func page(title: String, body: String) -> String {
        """
        <!doctype html>
        <html lang="en">
        <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="color-scheme" content="light dark">
        <title>\(e(title))</title>
        <style>\(css)</style>
        </head>
        <body>
        <main>
        \(body)
        </main>
        </body>
        </html>
        """
    }

    // Type scale (plans/design-system.md): body 16/1.55; h1 28/600; h2 20/600;
    // h3 17/600; meta 14 secondary; code 13 mono. One accent, no decoration.
    private static let css = """
        :root{--fg:#1d1d1f;--fg2:#6e6e73;--bg:#fff;--bg2:#f5f5f7;--rule:#d2d2d7;--link:#0066cc;--up:#248a3d;--down:#86868b}
        @media (prefers-color-scheme:dark){:root{--fg:#f5f5f7;--fg2:#a1a1a6;--bg:#1d1d1f;--bg2:#2c2c2e;--rule:#424245;--link:#4da3ff;--up:#30d158;--down:#8e8e93}}
        *{box-sizing:border-box}
        html{-webkit-text-size-adjust:100%}
        body{margin:0;background:var(--bg);color:var(--fg);font:400 1rem/1.55 -apple-system,BlinkMacSystemFont,"SF Pro Text","Helvetica Neue",sans-serif}
        main{max-width:44rem;margin:0 auto;padding:3rem 1.5rem 4rem}
        h1{font-size:1.75rem;font-weight:600;line-height:1.2;letter-spacing:-.01em;margin:0 0 .5rem}
        h2{font-size:1.25rem;font-weight:600;line-height:1.3;margin:2.25rem 0 .75rem}
        h3{font-size:1.0625rem;font-weight:600;line-height:1.4;margin:1.5rem 0 .5rem}
        p,ul,ol,dl,pre,table,blockquote{margin:0 0 1rem}
        ul,ol{padding-left:1.5rem}
        li{margin:.25rem 0}
        a{color:var(--link);text-decoration:none}
        a:hover{text-decoration:underline}
        strong{font-weight:600}
        code,.mono{font-family:ui-monospace,"SF Mono",Menlo,monospace;font-size:.875em}
        pre{background:var(--bg2);border-radius:8px;padding:.875rem 1rem;overflow-x:auto;line-height:1.5}
        pre code{font-size:.8125rem}
        blockquote{margin-left:0;padding-left:1rem;border-left:3px solid var(--rule);color:var(--fg2)}
        .meta{font-size:.875rem;color:var(--fg2)}
        header .meta{margin:0}
        table{border-collapse:collapse;width:100%;font-size:.9375rem}
        th{text-align:left;font-weight:600;font-size:.875rem;color:var(--fg2);border-bottom:1px solid var(--rule);padding:.375rem .75rem .375rem 0}
        td{border-bottom:1px solid var(--rule);padding:.5rem .75rem .5rem 0}
        dl{display:grid;grid-template-columns:max-content 1fr;gap:.25rem 1rem}
        dt{color:var(--fg2)}
        dd{margin:0}
        .up{color:var(--up)}
        .down{color:var(--down)}
        """
}
